<?php
include_once('Circle.php');

class cylinder extends Circle
{
    public $height;

    public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }

    public function setHeight($height)
    {
        $this->height = $height;
    }

    public function getHeight()
    {
        return $this->height;
    }

    public function area_around_the_cylinder()
    {
        return floor(2 * pi() * $this->radius * $this->height);
    }

    public function total_cylindrical_area()
    {
        return floor(2 * pi() * $this->radius * ($this->radius + $this->height ));
    }
}